### ISSUE TITLE
mistype

### ISSUE THREAD

**Issue by snotfod** [iovidius/BarryBox#5]
Hi, I found a mistype. 
Small f in "WifiManager.h" should be big F as "WiFiManager.h" or compile will fail.

**Comment by joszuijderwijk** [comment]
Hi! Thanks for pointing it out. Where did you find the faulty line? I just compiled the code successfully and it seems to be correct in [BarryBox.ino](https://github.com/iovidius/BarryBox/blob/main/ESP32/BarryBox/BarryBox.ino#L9)

**Comment by snotfod** [comment]
Sorry I can see there is no error here so I must have created it myself. Sorry for the inconvenience.

**Comment by joszuijderwijk** [comment]
That's okay! :) Glad it's resolved
