### ISSUE TITLE
Hello ^^ Compilation error how to fix ?

### ISSUE THREAD

**Issue by tweastevil** [iovidius/BarryBox#7]
I am using Arduino IDE 2.32 with ESP32 SDK version 2.0.13. When I compile, the following section of the code shows an error message:
Compilation error: reference to 'byte' is ambiguous
The code it points to is:

// Handle incoming messages
void callback(char *topic, byte *payload, unsigned int len)
{

  String msg = ""; // payload
  for (int i = 0; i < len; i++)
  {
    msg += ((char)payload[i]);
  }

  Streamable *s = new Streamable();

  if (strcmp(topic, tts_channel.c_str()) == 0)
  {

    // Got TTS message
    s->SetType(SAY);

    StaticJsonDocument<256> doc;
    deserializeJson(doc, payload);

    if (!doc.isNull())
    {
      const char *text = doc["text"];
      const char *lang = doc["language"];

      s->SetData(text);

      if (isValidLanguage(lang))
        s->SetLanguage(lang);
      else
        s->SetLanguage(DEFAULT_LANGUAGE);
    }
    else
    {
      s->SetData(msg);
    }
  }
  else if (strcmp(topic, stream_channel.c_str()) == 0)
  {
    if (msg == "stop")
      audio.stopSong();
    else
    {
      s->SetType(STREAM);
      s->SetData(msg);
    }
  }
  else if (strcmp(topic, soundboard_channel.c_str()) == 0)
  {
    s->SetType(SOUND);
    s->SetData(msg);
  }

  if (!Q.isFull())
    Q.enqueue(s);
}

**Comment by joszuijderwijk** [comment]
I'm not able to reproduce this error (Arduino Nano ESP32). Which board have you selected?

**Comment by tweastevil** [comment]
> I'm not able to reproduce this error (Arduino Nano ESP32). Which board have you selected?

sorry, The information I provided was not clear enough. The development board I am using is the ESP32-WROOM-32.

**Comment by joszuijderwijk** [comment]
changing `byte` to `unsigned char` should help.

**Comment by tweastevil** [comment]
Hello,

I have tried changing the callback function to unsigned char, but it still fails to compile. It shows the following error:

`In file included from F:\文件\Arduino\BarryBox\ESP32\BarryBox\BarryBox.ino:9:
f:\���\Arduino\libraries\WiFiManager/WiFiManager.h:536:11: error: reference to 'byte' is ambiguous
  536 |     const byte    DNS_PORT                = 53;
      |           ^~~~
In file included from c:\users\sensor\appdata\local\arduino15\packages\esp32\tools\esp-x32\2302\xtensa-esp32-elf\include\c++\12.2.0\cmath:42,
                 from c:\users\sensor\appdata\local\arduino15\packages\esp32\tools\esp-x32\2302\xtensa-esp32-elf\include\c++\12.2.0\math.h:36,
                 from C:\Users\sensor\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.2\cores\esp32/esp32-hal.h:30,
                 from C:\Users\sensor\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.2\cores\esp32/Arduino.h:36,
                 from C:\Users\sensor\AppData\Local\Temp\arduino\sketches\25D2D9FD5C81ADC1C8A2EDEB9B2CF2C1\sketch\BarryBox.ino.cpp:1:
c:\users\sensor\appdata\local\arduino15\packages\esp32\tools\esp-x32\2302\xtensa-esp32-elf\include\c++\12.2.0\bits\cpp_type_traits.h:406:30: note: candidates are: 'enum class std::byte'
  406 |   enum class byte : unsigned char;
      |                              ^~~~
C:\Users\sensor\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.2\cores\esp32/Arduino.h:149:17: note:                 'typedef uint8_t byte'
  149 | typedef uint8_t byte;
      |                 ^~~~
`

**Comment by joszuijderwijk** [comment]
Seems to be a bug within WifiManager library. Changing `byte` to `uint8_t` fixes this.

**Comment by joszuijderwijk** [comment]
Created a pull request https://github.com/tzapu/WiFiManager/pull/1748
